services:
  csvserver:
    image: infracloudio/csvserver:latest
    ports:
      - "9393:9300"
    env_file:
      - csvserver.env
    volumes:
      - /Users/virtuecloud/Desktop/solution/inputdata:/csvserver/inputdata
